mystr="Paras is a good boy"
print(len(mystr))
print(mystr[0:19])
# print(mystr[78]) //error
print(mystr[0:50])
print(mystr[0:5:2])
print(mystr[0:])
print(mystr[:3])
print(mystr[:])
print(mystr[::])
print(mystr[0:19:1])
print(mystr[0::2])
print(mystr[0::3])
print(mystr[::9])
print(mystr[::100])

print(mystr[-1:0])
print(mystr[-4:])
# print(mystr[-4:-2])
# print(mystr[15:17])
# print(mystr[15:17:-1])
# print(mystr[::-1])
# print(mystr[::-2])
#
# print(mystr.isalnum())
# print(mystr.isalpha())
# print(mystr.endswith("boy"))
# print(mystr.endswith("bosdy"))
# print(mystr.count("a"))
# print(mystr.count("P"))
# print(mystr.capitalize())
# print(mystr.find("is"))
# print(mystr.lower())
# print(mystr.upper())
# print(mystr.replace("is","are"))
